### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lruozzi9** [webgriffe/SyliusActiveCampaignPlugin#9]
- [x] Specificare che c'è da implementare la ActiveCampaignAwareInterface sul Channel. L'activeCampaingId sarà l'ID della connection creata su AC. Farlo anche per tutte le altre entità e spiegare come funziona.
- [x] Spiegare la questione riguardante la issue #21 e come fare
- [x] Spiegare la questione riguardante la issue #23 e come fare
- [x] Spiegare comandi
- [x] Spiegare automatismi già esistenti (EventListener)
- [x] Add image type doc
- [x] Moved out of this issue: #30
